version: '3.8'

services:
  userservice:
    image: userservice:latest
    networks:
      - backend
    build:
      context: .
      dockerfile: User Service/Dockerfile
networks:
  backend:
    name: backend
    external: true
    driver: bridge
